//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoamenShalaby.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quntra_project : DbContext
    {
        public quntra_project()
            : base("name=quntra_project")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<Gard> Gards { get; set; }
        public virtual DbSet<Muarden> Muardens { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<rb7> rb7 { get; set; }
        public virtual DbSet<Trans_Customer> Trans_Customer { get; set; }
        public virtual DbSet<Trans_Muarden> Trans_Muarden { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
