//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoamenShalaby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rb7
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> Price_Total { get; set; }
        public Nullable<decimal> Qty_Total_Saled { get; set; }
        public Nullable<decimal> rb71 { get; set; }
    }
}
