//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoamenShalaby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_Customer
    {
        public int id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> cash { get; set; }
        public Nullable<decimal> reminder { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
