//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoamenShalaby.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public Nullable<int> saled_Qty { get; set; }
        public Nullable<decimal> saled_Price { get; set; }
        public Nullable<int> Products_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string date { get; set; }
    
        public virtual product product { get; set; }
    }
}
